### ISSUE TITLE
希望提供仅声音驱动模式，不需要输入refvideo

### ISSUE THREAD

**Issue by Aiden-Yu** [haomole/Comfyui-SadTalker#3]
SadTalker官网使用说明：

python inference.py --driven_audio <audio.wav> \
                    --source_image <video.mp4 or picture.png> \
                    --enhancer gfpgan

**Comment by Aiden-Yu** [comment]
useRefVideo 设为 false，但仍然提示要输入Video

Prompt outputs failed validation LoadRefVideo: - Required input is missing: video

**Comment by haomole** [comment]
![image](https://github.com/user-attachments/assets/6bf71904-58f9-4e0b-91a8-7dda3ed1e806)
还没找到更改为可选项的方法......
