### ISSUE TITLE
gfpgan onnex support.

### ISSUE THREAD

**Issue by shivshankar11** [haomole/Comfyui-SadTalker#4]
hi can you add gfpgan onnx format from here. its faster.
https://github.com/facefusion/facefusion-assets

**Comment by Aiden-Yu** [comment]
另外 gfpgan 模型文件放到 comfyui 根目录很奇怪，细节控表示有点难受

**Comment by haomole** [comment]
hi, the download of gfpgan is the download address provided by the original SadTalker. If I have time, I will find it and revise it and reply to you.

**Comment by haomole** [comment]
> 另外 gfpgan 模型文件放到 comfyui 根目录很奇怪，细节控表示有点难受

会考虑修改，目前时间不太允许改这些
